jersey:
  urlPattern: '/api/*'

log:
  loggers:
    "io.swagger.v3.core.converter":
      level: debug
    "org.example.agrest.openapi":
      level: debug

swagger:
  specs:
    default:
      pathJson: "model/openapi.json"
      pathYaml: "model/openapi.yaml"
      overrideSpec: "classpath:openapi-header.yml"
      resourcePackages:
        - "org.example.agrest.api"

swaggerui:
  default:
    specPath: "api/model/openapi.json"
